config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :posts do
  	resources :comments
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		   	 :recoverable, :rememberable, :trackable, :validatable
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comments_params)

		# Email delivery is off until I find satisfying mailing provider
		CommentMailer.comment_created(current_user, @post.user, @comment.content)#.deliver
		redirect_to post_path(@post)
	end

	private

		def comments_params
			params.require(:comment).permit(:content)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to posts_path
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.order(:created_at).includes(:user)
    @posts = Post.order("users.name").joins(:user).select("posts.*, users.name as user_name")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.includes(:post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = current_user
    @post = @user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        # Email delivery is off until I find satisfying mailing provider
        PostMailer.post_created(@user)#.deliver 
        
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	private
		def sign_up_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def account_update_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.haml
- @comments.each do |comment|
	%p= comment.content

app/views/comments/_form.html.haml
= form_for([@post, @post.comments.build]) do |f|

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit

app/views/home/index.html.haml
%h1#title Simple Blog
%p Welcome to the simple blog, where you can write posts or read other users' posts. All you have to do is register, or if you already have an account, sign in. Enjoy! 

app/views/layouts/_header.html.haml
%header
	.navbar
		= link_to "simple blog", root_path, id: "logo"
		%nav
			%ul.navbar-right
				- if user_signed_in?
					%li= link_to "Posts", posts_path
					%li= link_to "Sign out", destroy_user_session_path, :method => 'delete'
				- else
					%li= link_to "Sign In", new_user_session_path
					%li= link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mailapp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{ :class => "alert-#{message_type}" }
          = message
    

    = yield

app/views/posts/_form.html.haml
= form_for(post) do |f|
  - if post.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%p#notice= notice
%h1 Posts
%table
  %thead
    %tr
      %th User
      %th Title
      %th Content
      %th{:colspan => "3"}
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.user_name
        %td= post.title
        %td= post.content
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @post.title
%p
  %strong Content:
  = @post.content

%h3 Comments

= render "comments/comments"

%br/

= render "comments/form"
= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back', posts_path